#!/usr/bin/env bash

MONITORS_DIR=${HOME}/.config/dbarthe.monitors

CURRENT_SETTINGS=${HOME}/.config/monitors.xml

main() {
    setup
    parse_and_exec_cmd $@
}

setup() {
    mkdir -p "$MONITORS_DIR"
}

parse_and_exec_cmd() {
    case $1 in
    save)
        monitors_save $@
    ;;
    restore)
        monitors_restore $@
    ;;
    list)
        monitors_list $@
    ;;
    *|help)
        monitors_help $@
    esac
}

monitors_help() {
    echo "usage: $0 [cmd] [args...]"
    echo ""
    echo "Use the following cmd:"
    echo "    save <name>       save current monitors settings"
    echo "    restore <name>    restore monitors settings you saved"
    echo "    list              list available settings"
    echo "    help              print this help"
}

monitors_restore() {
    if [ $# -lt 2 ]; then
        monitors_help
        exit 1
    fi
    name=$2

    if [ ! -e "$MONITORS_DIR/$name" ]; then
        echo "error: settings $name does not exist"
        exit 1
    fi
    apply_monitor_config "$MONITORS_DIR/$name"
}

monitors_save() {
    if [ $# -lt 2 ]; then
        monitors_help
        exit 1
    fi
    name=$2
    cp "$CURRENT_SETTINGS" "$MONITORS_DIR/$name"
}

monitors_list() {
    ls $MONITORS_DIR
}


apply_monitor_config() {

# -------------------------------------------------
#  Get monitors configuration from monitor.xml and apply it for current user session.
#  In case of multiple definitions in monitor.xml only first one is used.
#
#  See http://bernaerts.dyndns.org/linux/74-ubuntu/309-ubuntu-dual-display-monitor-position-lost
#  for instructions
#
#  Parameters :
#    $1 : waiting time in sec. before forcing configuration (optional)
#
#  Revision history :
#    19/04/2014, V1.0 - Creation by N. Bernaerts
#    10/07/2014, V1.1 - Wait 5 seconds for X to fully initialize
#    01/09/2014, V1.2 - Correct NULL file bug (thanks to Ivan Harmady) and handle rotation
#    07/10/2014, V1.3 - Add monitors size and rate handling (idea from jescalante)
#    08/10/2014, V1.4 - Handle primary display parameter
#    08/12/2014, V1.5 - Waiting time in seconds becomes a parameter
# ------------------------------------------------

    # monitor.xml path
    MONITOR_XML="$1"

    # get number of declared monitors
    NUM=$(xmllint --xpath 'count(//monitors/configuration['1']/output)' $MONITOR_XML)

    # loop thru declared monitors to create the command line parameters
    for (( i=1; i<=$NUM; i++)); do
      # get attributes of current monitor (name and x & y positions)
      NAME=$(xmllint --xpath 'string(//monitors/configuration['1']/output['$i']/@name)' $MONITOR_XML 2>/dev/null)
      POS_X=$(xmllint --xpath '//monitors/configuration['1']/output['$i']/x/text()' $MONITOR_XML 2>/dev/null)
      POS_Y=$(xmllint --xpath '//monitors/configuration['1']/output['$i']/y/text()' $MONITOR_XML 2>/dev/null)
      ROTATE=$(xmllint --xpath '//monitors/configuration['1']/output['$i']/rotation/text()' $MONITOR_XML 2>/dev/null)
      WIDTH=$(xmllint --xpath '//monitors/configuration['1']/output['$i']/width/text()' $MONITOR_XML 2>/dev/null)
      HEIGHT=$(xmllint --xpath '//monitors/configuration['1']/output['$i']/height/text()' $MONITOR_XML 2>/dev/null)
      RATE=$(xmllint --xpath '//monitors/configuration['1']/output['$i']/rate/text()' $MONITOR_XML 2>/dev/null)
      PRIMARY=$(xmllint --xpath '//monitors/configuration['1']/output['$i']/primary/text()' $MONITOR_XML 2>/dev/null)

      # if position is defined for current monitor, add its position and orientation to command line parameters
      [ -n "$POS_X" ] && PARAM_ARR=("${PARAM_ARR[@]}" "--output" "$NAME" "--pos" "${POS_X}x${POS_Y}" "--fbmm" "${WIDTH}x${HEIGHT}" "--rate" "$RATE" "--rotate" "$ROTATE")

      # if monitor is defined as primary, adds it to command line parameters
      [ "$PRIMARY" = "yes" ] && PARAM_ARR=("${PARAM_ARR[@]}" "--primary")
    done

    # if needed, wait for some seconds (for X to finish initialisation)
    [ -n "$2" ] && sleep $2

    # position all monitors
    xrandr "${PARAM_ARR[@]}"
}

main $@